---
title: "Introduction to datatools"
author: "Pierre Mercklé, Anton Perdoncin and Baptiste Coulmont"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to firstnamer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

More and more social scientists and historians are using R in their research. Numerous packages already exist, providing either general tools for data manipulation and processing ([tidyverse](https://www.tidyverse.org), [questionr](https://cran.r-project.org/web/packages/questionr/index.html), etc.), or specific tools related to specific families of methods (network analysis, geometric data analysis, longitudinal analysis, etc.).

However, specific tools to facilitate the work of researchers struggling with data entry, coding and presentation are not always available, or only in a scattered manner. For example: importing the various tabs of a spreadsheet into R, standardizing the automatic generation of html, docx and pdf reports from Rmd files, quickly and easily formatting simple tables and graphs, determining the gender of first names, or comparing and matching first or last names.

This is why we are developing the `datatatools` package that brings together functions useful for historians and social scientists. The package is still under development, and -- for now -- only offers a small number of functions to transform Eastern European names and surnames into soundex codes (according to the Daitch-Mokotov algorithm), and to compute the probability of belonging to gender categories for names belonging to the French National Institute of Statistics (INSEE) first name database.

Other functions are under development... 
