---
title: "Introduction to firstnamer"
author: "Baptiste Coulmont & Pierre Mercklé"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to firstnamer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


A '[firstnamer](https://www.urbandictionary.com/define.php?term=Firstnamer)' is someone who more than necessary refers to unknown, non-present people by intentionnally using only their first names. 'Firstnaming' is often used to make others feel like they do not know the people everybody is supposed to know. 

But beyond fatuity and distinction strategies, what's behing a first name? This is the purpose of the firstnamer package to help uncover the unsuspected amount of information that first narmes carry with them. It is designed as a set of function that help retrieve these informations and handle first names.

This document introduces you to the general principles of first name information handling, and it shows how to apply the basic set of tools included in the firstnamer package to your data.
